set number
set autoindent
set smartindent
set expandtab
set modifiable
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,iso-2022-jp,euc-jp,ucs-2,cp932,sjis
set tabstop=2
set shiftwidth=2
set cursorline
set colorcolumn=80,120
highlight ColorColumn guibg=#202020 ctermbg=lightgray
set number
set showmode
set showmatch
set title
set backspace=indent,eol,start
syntax on
